// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  tutorialSidebar: [
		{
      type: "autogenerated",
      dirName: ".",
    },
    {
      type: "category",
      label: "SUPPORT",
      items: [
        { type: "link", label: "Slack", href: "https://gridai-community.slack.com", className: "slack-icon" },
        { type: "link", label: "Mail", href: "mailto:support@grid.ai", className: "mail-icon" },
      ],
    },
  ],
};

module.exports = sidebars;

// { type: "doc", id: "", label: "" },
